Version: 1
Devices:
  10468613300743582032:
    Name: screen
    Type: Screen
    Screen:
      Width: 128
      Height: 64
  111111:
    Name: cpu
    Type: Engine
    ConnectedCpu:
      []
  16495467231675324418:
    Name: worstscreen
    Type: Engine
    ConnectedCpu:
      []